[project]
name = "Project-Diane"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.1",
    "markdown>=3.10.3",
    "pillow>=12.3.0",
    "pygame>=2.6.1",
    "rpi-lgpio>=0.6",
    "spidev>=3.8",
]

[project.scripts]
project_diane = "project_diane:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "Project-Diane",
]
